apiVersion: v1
kind: Service
metadata:
  name: type-b-service
  namespace: lizzoslunch
spec:
  selector:
    app: type-b
  ports:
    - name: http
      port: 80             
      targetPort: 5000 
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: type-b
  namespace: lizzoslunch
spec:
  host: type-b-service.lizzoslunch.svc.cluster.local #
  subsets:
    - name: stable
      labels:
        app: type-b